### ISSUE TITLE
Eu como funcionário desejo visualizar dois gráficos simultaneamente em janelas ou abas diferentes

### ISSUE THREAD

**Issue by IagoCarvalho** [fga-gpp-mds/2016.2-SME_UnB#36]

**Comment by TiagoAssuncao** [comment]
A página está funcionando corretamente em condições de corrida, porém, os gráficos estão quebrando na produção.
![captura de tela de 2016-10-29 09 09 44](https://cloud.githubusercontent.com/assets/8422747/19829121/ab42cae6-9db7-11e6-9aea-b86c8f506b9b.png)
